SAP/ai-sdk

- docs-java/release-notes/release-notes-0-to-14.mdx
- docusaurus.config.js
I added an Algolia crawler for the search bar of the AI SDK documentation
> Added Algolia search crawler

- docs-java/release-notes/release-notes-0-to-14.mdx
Add the SAP Cloud SDK 1.6.0 release notes
> Java: Add release notes for release 1.6.0

- docs-java/release-notes/release-notes-0-to-14.mdx
Reverted my release workflow test
> Revert release notes test

- docs-java/ai-core/prompt-registry.mdx
We updated the Prompt Registry spec and those are the changes
> Java: Prompt Registry new spec

- docs-java/foundation-models/openai/chat-completion.mdx
Adding documentation for full tool call use case with convenience api.
> [Java][OpenAI] Tool call convenience documentation

- docs-java/orchestration/chat-completion.mdx
- docs-java/release-notes/release-notes-0-to-14.mdx
- src/components/data/features.js
- styles/config/vocabularies/SAP/accept.txt
> Add doc links to feature matrix page

- docs-java/overview.mdx
> chore: Introduce SDK full name and shorter name

- docs-js/overview.mdx
- docusaurus.config.js
- sidebarsDocsJs.js
- src/components/FeatureTable.js
- src/components/data/table-layouts.js
- src/pages/components/HomepageFeatures.js
- src/pages/index.js
> chore: Add python placeholder

- docs-js/orchestration/chat-completion.mdx
In order to show more subtitles, use `##` and `###` for subtitles, as subtitles with `####` are not shown on the right side.
> [JS] chore: Use second level subtitle

- sidebarsDocsJs.js
This PR adds the JS release notes to the sidebar, to make it easily accessible.
> [JS] chore: add release notes to sidebar

- src/pages/components/HomepageFeatures.js
> chore: Link to python doc

- docs-js/orchestration/chat-completion.mdx
- styles/config/vocabularies/SAP/accept.txt
> chore: Add docs on local prompt template

- docs-js/release-notes.mdx
Manual update due to failed bump
> chore: update JS release notes

- docs-js/release-notes.mdx
> update release notes

- docs-js/foundation-models/openai/chat-completion.mdx
Add a new section for function calling with OpenAI client.
> [JS] feat: Add documentation for OpenAI tool call

- docusaurus.config.js
Add links for Cloud SDK in footer.
> Add links for Cloud SDK

- docs-java/spring-ai/orchestration.mdx
Adding docs about using response format with Spring AI: https://github.com/SAP/ai-sdk-java/pull/422
> [Java]docs: Add docs about using response format with Spring AI

- docs-js/release-notes.mdx
Remove `[Core Modules]` in js release note.
> [JS] Update release-notes.mdx

- README.md
> chore: remove warning from the Readme 

- docs-java/foundation-models/openai/chat-completion.mdx
- docs-java/spring-ai/orchestration.mdx
Orchestration enabled tool execution, We can remove the workaround.
> Java 1.8.0: Orchestration Tool Execution

- docs-js/foundation-models/foundation-models.mdx
- docs-js/getting-started.mdx
- docs-js/langchain/openai.mdx
- docs-js/overview.mdx
- docs-js/tutorials/getting-started-with-agents.mdx
- docs-js/tutorials/getting-started-with-agents/openai-langchain.mdx
- sidebarsDocsJs.js
- styles/config/vocabularies/SAP/accept.txt
Closes https://github.com/SAP/ai-sdk-js-backlog/issues/175
Tutorial code: https://github.com/SAP/ai-sdk-js/tree/tutorial-agent/sample-code/src/tutorials
> chore: Add agent based workflow tutorial using bindTools and Langgraph

- docs-js/faq.mdx
- sidebarsDocsJs.js
> [JS] Add a Q/A section for CAP LLM Plugin 

- docs-js/orchestration/chat-completion.mdx
We recommend that zod v4 should be used, which has native support for zod to json schema functionality.
> [JS] Use zod v4 in doc

- docs-js/overview.mdx
The deprecated models and their replacements are updated.
SAP/ai-sdk-js-backlog#360.
> chore: Update deprecated models

- docs-js/overview.mdx
Added note in prerequisites to upgrade from node 20.
> chore: Add note to upgrade from node 20
